service: kanotan-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
  time:
    handler: handler.time
