service: kanotan-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    timeout: 10
    events:
      - http:
          path: kanotan-serverless/hello
          method: get
  time:
    handler: handler.time
    timeout: 10
    events:
      - http:
          path: kanotan-serverless/time
          method: get

